repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: check-ast
    -   id: debug-statements

-   repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2
    hooks:
    -   id: pydocstyle
        exclude: blog/migrations/

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.5.0
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
        args: [ --whitespaces-count, '4' ]  # defaults to: 4

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    -   id: mypy

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        args:
        - --load-plugins=pylint_django
        - --good-names=urlpatterns
        exclude: blog/migrations/
        language: system
        types: [python]
