language: python
python:
  - 3.8
  - 3.7
cache: pip
env:
  global:
    - KPI_SECRET_KEY="DummySecretKeyForUseOnTravis"
script:
  - python manage.py test
jobs:
  include:
    - install:
        - pip install -r travis-requirements.txt
      script: pre-commit run --all-files
