language: python
python:
  - 3.8
  - 3.7
cache: pip
script:
  - python manage.py test
jobs:
  include:
    - install:
        - pip install -r travis-requirements.txt
      script: pre-commit run --all-files
